# Generated by Django 6.0.3 on 2026-05-06 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categoryimage_category_extra_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='extra_images',
        ),
        migrations.AddField(
            model_name='categoryimage',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='main.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
    ]
