# Generated by Django 6.0.3 on 2026-05-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Процент скидки на товар (0-100)', verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Участвует в распродаже'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Автоматически рассчитывается из цены и процента скидки', max_digits=10, verbose_name='Цена со скидкой'),
        ),
    ]
