# Generated by Django 6.0.3 on 2026-05-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_category_extra_images_categoryimage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение 4'),
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
