# Generated by Django 6.0.3 on 2026-05-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('heleket', 'Heleket'), ('cash', 'Наличные'), ('card', 'Картой')], max_length=20, null=True, verbose_name='Платежный провайдер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возврат'), ('waiting_pickup', 'Ожидает выдачи'), ('received_paid', 'Получен и оплачен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возврат'), ('waiting_pickup', 'Ожидает выдачи'), ('received_paid', 'Получен и оплачен')], max_length=20, verbose_name='Статус'),
        ),
    ]
