# Generated by Django 6.0.3 on 2026-05-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Ключ сессии'),
        ),
    ]
